// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempporalWS.Data;

namespace TempporalWS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("TempporalWS.Models.Producto", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(9999)
                        .HasColumnType("text");

                    b.Property<decimal>("Existencia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Codigo");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("TempporalWS.Models.ProductoTicket", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(9999)
                        .HasColumnType("text");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Codigo");

                    b.ToTable("ProductosTicket");
                });

            modelBuilder.Entity("TempporalWS.Models.Ticket", b =>
                {
                    b.Property<int>("Folio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Fecha")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Fk_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Hora")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ListaProductosString")
                        .HasMaxLength(9999)
                        .HasColumnType("text");

                    b.Property<decimal>("TotalArticulos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalVenta")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Folio");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TempporalWS.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Password")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Rol")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
